### ISSUE TITLE
will this project support http3?

### ISSUE THREAD

**Issue by LetUsFlow** [Giftzwerg02/personal-webpage-server#1]
http3 ist BASED (on udp), which means that it is much cooler than http1 and http2. do you intend to support this futuristic protocol?

but i rellay want to express my happiness about this project, because the world ABSOLUTELY NEEDS another webserver, we really don't have enough other options.

**Comment by Giftzwerg02** [comment]
This project is dead.

**Comment by LetUsFlow** [comment]
this is very sad :(
i would ask you to mark the project as archived, so other people don't need to create an issue similar to this one.
if you are too scared of doing this, just add me as collaborator to the repo and i can help you with that.

**Comment by Giftzwerg02** [comment]
no

**Comment by LetUsFlow** [comment]
i know where you live

**Comment by Giftzwerg02** [comment]
Same!

**Comment by LetUsFlow** [comment]
well that's great
i might just come to your house in the middle of the night and archive this repo
(disclaimer for law enforcement: this is not an actual threat, giftzwerg02 and i are friends, i have proof for that)

**Comment by Giftzwerg02** [comment]
We are not friends :3

**Comment by LetUsFlow** [comment]
> We are not friends :3

uwu
